name: Publish Docker Image                      
on: push                       
jobs:                      
  push_docker_image_to_registry:                    
    name: Push Docker image to registry                   
    runs-on: ubuntu-latest                   
    steps:                  
      - name: Check out Repo                
        uses: actions/checkout@v3  
      - name: Login to Docker Hub               
        uses: docker/login-action@v2                
        with:             
          username: ${{ secrets.DOCKERHUB_USERNAME }}             
          password: ${{ secrets.DOCKERHUB_TOKEN }}     
      - name: Extract Metadata (Tags and Labels) for Docker Image                 
        id: meta               
        uses: docker/metadata-action@v4             
        with:            
          images: vickdocker2023/gitbuhactionrepo
      - name: Build and push                 
        uses: docker/build-push-action@v4              
        with:             
          context: .           
          push: true            
          tags: ${{ steps.meta.outputs.tags }}                 
          labels: ${{ steps.meta.output.labels }}
 
