name: Publish Docker Image                      
on: push                       
jobs:                      
  push_docker_image_to_registry:                    
    name: Push Docker image to registry                   
    runs-on: ubuntu-latest                   
    steps:                  
      - name: Check out Repo                
        uses: actions/checkout@v3  
      - name: Login to Docker Hub               
        uses: docker/login-action@v2                
        with:             
          username: ${{ varibles.DOCKERHUB_USERNAME }}             
          password: ${{ secrets.DOCKERHUB_TOKEN }}   
